# Generated by Django 4.2.5 on 2023-09-17 08:17

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                (
                    'address',
                    models.CharField(
                        max_length=44,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(32),
                            django.core.validators.MaxLengthValidator(44),
                        ],
                        verbose_name='address',
                    ),
                ),
                ('email', models.EmailField(blank=True, unique=True, default='', max_length=254, verbose_name='email')),
                ('moniker', models.CharField(blank=True, default='', max_length=250, verbose_name='moniker')),
                ('is_suspended', models.BooleanField(blank=True, default=False, verbose_name='is suspended')),
                ('suspension_reason', models.TextField(default='', verbose_name='suspension reason')),
                ('is_verified', models.BooleanField(blank=True, default=False, verbose_name='is verified')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
