# Generated by Django 4.2.5 on 2023-09-20 06:18

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                (
                    'balance',
                    models.DecimalField(
                        decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='balance'
                    ),
                ),
                ('provider_id', models.CharField(max_length=100, verbose_name='circle provider identifier')),
                (
                    'account',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='wallet',
                        to='accounts.account',
                        verbose_name='account',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WalletDepositAddress',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('address', models.CharField(max_length=200, unique=True, verbose_name='address')),
                (
                    'blockchain',
                    models.CharField(
                        choices=[
                            ('TRX', 'Tron'),
                            ('BASE', 'Base'),
                            ('SOL', 'Solana'),
                            ('MATIC', 'Matic'),
                            ('OP', 'Optimism'),
                            ('ARB', 'Arbitrum'),
                            ('ETH', 'Ethereum'),
                            ('ALGO', 'Algorand'),
                            ('AVAX', 'Avalanche'),
                        ],
                        max_length=100,
                        verbose_name='blockchain',
                    ),
                ),
                (
                    'wallet',
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deposit_addresses',
                        to='accounts.wallet',
                        verbose_name='wallet',
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name='walletdepositaddress',
            constraint=models.UniqueConstraint(
                fields=('address', 'wallet', 'blockchain'), name='wallet_address_and_chain_unique'
            ),
        ),
    ]
