# Generated by Django 4.2.5 on 2023-09-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_wallet_walletdepositaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='provider_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='circle provider identifier'),
        ),
    ]
