# Generated by Django 4.2.5 on 2023-09-26 00:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('accounts', '0003_alter_wallet_provider_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('caption', models.TextField(verbose_name='content caption')),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contents',
                        to='accounts.account',
                        verbose_name='account',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('s3_key', models.CharField(max_length=100, verbose_name='file path on s3')),
                (
                    'media_type',
                    models.CharField(
                        choices=[('image', 'Image'), ('video', 'Video')], max_length=20, verbose_name='media type'
                    ),
                ),
                (
                    'content',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='media',
                        to='contents.content',
                        verbose_name='content',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
