# Generated by Django 4.2.5 on 2023-10-11 10:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('creators', '0002_creator_banner_url_creator_image_url'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='creators.creator', verbose_name='likes'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('message', models.CharField(max_length=200, verbose_name='message')),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='my_comments',
                        to='creators.creator',
                        verbose_name='author',
                    ),
                ),
                (
                    'content',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='contents.content',
                        verbose_name='content',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
