# Generated by Django 4.2.5 on 2023-11-02 11:39

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="duration",
            field=models.DurationField(
                validators=[
                    django.core.validators.MinValueValidator(
                        datetime.timedelta(seconds=900)
                    ),
                    django.core.validators.MaxValueValidator(
                        datetime.timedelta(seconds=7200)
                    ),
                ],
                verbose_name="livestream duration",
            ),
        ),
    ]
