# Generated by Django 4.2.7 on 2023-11-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="livestream",
            name="start",
            field=models.DateTimeField(null=True, verbose_name="start timestamp"),
        ),
    ]
