# Generated by Django 4.2.5 on 2023-09-27 22:37

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0003_alter_wallet_provider_id'),
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livestream',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('start', models.DateTimeField(verbose_name='start timestamp')),
                (
                    'duration',
                    models.DurationField(
                        validators=[
                            django.core.validators.MinValueValidator(datetime.timedelta(seconds=600)),
                            django.core.validators.MaxValueValidator(datetime.timedelta(seconds=1800)),
                        ],
                        verbose_name='livestream duration',
                    ),
                ),
                (
                    'account',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='livestream',
                        to='accounts.account',
                        verbose_name='account',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
