# Generated by Django 4.2.5 on 2023-10-12 08:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('creators', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDetail',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('subscription_id', models.UUIDField(verbose_name='subscription id')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')],
                        max_length=10,
                        verbose_name='status',
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscribers',
                        to='creators.creator',
                        verbose_name='creator',
                    ),
                ),
                (
                    'subscriber',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subscriptions',
                        to='creators.creator',
                        verbose_name='subscriber',
                    ),
                ),
                (
                    'subscription_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='+',
                        to='contenttypes.contenttype',
                        verbose_name='subscription type',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='NFTSubscription',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('collection_name', models.TextField(verbose_name='collection name')),
                ('collection_image_url', models.TextField(verbose_name='collection image url')),
                ('collection_description', models.TextField(verbose_name='collection description')),
                ('collection_address', models.CharField(max_length=44, verbose_name='collection address')),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, verbose_name='status'
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='nft_subscriptions',
                        to='creators.creator',
                        verbose_name='creator',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MonetarySubscription',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='amount')),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, verbose_name='status'
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='monetary_subscriptions',
                        to='creators.creator',
                        verbose_name='creator',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FreeSubscription',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                (
                    'status',
                    models.CharField(
                        choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=10, verbose_name='status'
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='free_subscriptions',
                        to='creators.creator',
                        verbose_name='creator',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='subscriptiondetail',
            constraint=models.UniqueConstraint(fields=('creator', 'subscriber'), name='creator_subscriber_unique'),
        ),
    ]
