# Generated by Django 4.2.7 on 2023-11-13 17:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                ("payload", models.JSONField(verbose_name="payload")),
                (
                    "message_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="message identifier"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed")],
                        max_length=10,
                        verbose_name="status",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("transfers", "Transfers"),
                            ("subscription confirmation", "Subscription Confirmation"),
                        ],
                        max_length=50,
                        verbose_name="notification type",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
