# Generated by Django 4.2.5 on 2023-10-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('creators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='banner_url',
            field=models.URLField(default='', verbose_name='banner url'),
        ),
        migrations.AddField(
            model_name='creator',
            name='image_url',
            field=models.URLField(default='', verbose_name='image url'),
        ),
    ]
