# Generated by Django 4.2.7 on 2023-11-14 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("creators", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creator",
            name="spam_verification_tx",
        ),
        migrations.CreateModel(
            name="WalletAuthenticationRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "nonce",
                    models.CharField(max_length=100, unique=True, verbose_name="nonce"),
                ),
                (
                    "transaction_reference",
                    models.CharField(
                        max_length=200,
                        unique=True,
                        verbose_name="transaction reference",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_authentication_records",
                        to="creators.creator",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
